### ISSUE TITLE
Suggestion to add a license file to the repository

### ISSUE THREAD

**Issue by OSSLicenseEnforcer** [KingRainbow44/Grasscutter-Rewrite#9]
Hello! I came across your code and I was wondering if you have considered adding a license file to your repository. A license file is a way of letting others know how they can use or modify your code legally. Without a license file, your code is technically not open source and no one can use it without your permission. This might limit the potential impact and reach of your project. GitHub recommends that you include a license in your repository to let others know how can your code be used and built upon (Source: [Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)).  If you are interested in making your project open source, you can check out [Choosing a license](https://choosealicense.com/no-permission/) to learn more about the different types of licenses and their benefits. 

To add a license file to your repository, you can follow the steps in this guide: [Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also read this article for more information on open source licensing: [Open Source Licensing Guide](https://github.com/readme/guides/open-source-licensing).

**Comment by OSSLicenseEnforcer** [comment]
Dear Authors,

We believe that our earlier communication could not reach you due to some technical issues with the communication on our end, so sending a gentle ping for you to kindly address the issue.

Regards
OSSLicenseEnforcer

**Comment by nitrog0d** [comment]
"Dear Authors,

We believe that our earlier communication could not reach you due to some technical issues with the communication on our end" 🤓🤓🤓🤓🤓

**Comment by lilmayofuksu** [comment]
🤓

**Comment by nitrog0d** [comment]
honestly shut up "Joined 5 days ago" 🤣 🤓🤓🤓

**Comment by nitrog0d** [comment]
ur being an annoyance on github repos reconsider life please.

**Comment by memetrollsXD** [comment]
kill yourself

**Comment by TotallyNotOndre** [comment]
🤓

**Comment by nitrog0d** [comment]
report for spam, annoying fuck

**Comment by Arikatsu** [comment]
💀

**Comment by TotallyNotOndre** [comment]
Hello🤓! I cum on your code💦💦💦 and I was wondering if you have considered adding a sex😈 to your repository😭😭😭. A sex file is a way of letting others know how they can shit on your code legally🤓🤓🤓. Without a sex file, your code is technically not cunny😭 and no one can use it without your cum💦💦💦. This might limit the potential iq of your project🤓. GitHub recommends that you include a sex😈 in your repository to let others know how can your cum be used and builtin SFM porn (Source: [SFM Porn tutorial part 6/9](https://www.kawaiidetective.com/tutorials/sfm-porn-tutorial-a-basic-animation/))🍆🍆. If you are interested in making your cum open source🍆😭😭😭, you can check out [💦Cum donorship💦](https://fertilityport.com/sperm-donation/) to learn more about the different types of cum💦💦💦 and their benefits😈.
